---
- name: This playbook will install/configure the ec2 Instances
  hosts: all
  become: yes
  tasks:
    - name: Install updates
      apt:
        update_cache: yes
        upgrade: yes
    
    - name: Install Apache
      apt:
        name: apache2
        state: present
    
    - name: Start and enable the service
      service:
        name: apache2
        state: started
        enabled: true    
